project: node-burn

workdir:
  remote: ${FIRECREST_SCRATCH}/fcw-node-burn-${FCW_NODE_BURN_RUN_ID}
  local: .

directories:
  config:
    type: in

containers:
  node-burn:
    file: ./env/Dockerfile.multistage
    tag: node-burn:12.4.1-runtime-ubuntu22.04
    remote_path: ./ce-images/
    toml: ./env/node-burn.toml
    platform: linux/arm64
    build_args:
      BASE_IMAGE: nvidia/cuda:12.4.1-devel-ubuntu22.04
      RUNTIME_BASE_IMAGE: nvidia/cuda:12.4.1-runtime-ubuntu22.04
      NODEBURN_COMMIT_ID: be4f759
    local_stages: [download, runtime-download]
    remote_stage: build-offline

jobs:
  node-burn:
    script: slurm/submit-node-burn.sh
    container: node-burn
    time: "1:00:00"
    nodes: 4
